// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj_1aFOyXHxWbALPw8SBLohdKXGwAE8Kc',
    appId: '1:445802360436:web:6f3df06128d096c731eb21',
    messagingSenderId: '445802360436',
    projectId: 'sams-app-e4656',
    authDomain: 'sams-app-e4656.firebaseapp.com',
    storageBucket: 'sams-app-e4656.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSPmQtYIEz14gJzzsqZ2mUIKt9t-Y7a74',
    appId: '1:445802360436:ios:5f5d0d6bfdb0b32231eb21',
    messagingSenderId: '445802360436',
    projectId: 'sams-app-e4656',
    storageBucket: 'sams-app-e4656.firebasestorage.app',
    iosBundleId: 'com.example.sams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSPmQtYIEz14gJzzsqZ2mUIKt9t-Y7a74',
    appId: '1:445802360436:ios:5f5d0d6bfdb0b32231eb21',
    messagingSenderId: '445802360436',
    projectId: 'sams-app-e4656',
    storageBucket: 'sams-app-e4656.firebasestorage.app',
    iosBundleId: 'com.example.sams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj_1aFOyXHxWbALPw8SBLohdKXGwAE8Kc',
    appId: '1:445802360436:web:80666005bedc118a31eb21',
    messagingSenderId: '445802360436',
    projectId: 'sams-app-e4656',
    authDomain: 'sams-app-e4656.firebaseapp.com',
    storageBucket: 'sams-app-e4656.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGFwC1Gepzl-ZJKm5hu4fXFRfbR4QquSA',
    appId: '1:445802360436:android:888320d7e10859e131eb21',
    messagingSenderId: '445802360436',
    projectId: 'sams-app-e4656',
    storageBucket: 'sams-app-e4656.firebasestorage.app',
  );
}
